#!/bin/sh
#keys
setxkbmap -model pc105 -layout "us,bg(phonetic)" -option "grp:alt_shift_toggle" 
sleep 1
xmodmap ~/.Xmodmap &
#comms
pgrep pidgin &> /dev/null || /usr/bin/pidgin &
#semafors
sleep 5
bash ~/bin/semafor1.sh &
#wear eye protection
pgrep safeeyes &> /dev/null || /usr/bin/safeeyes &
pgrep redshift &> /dev/null || /usr/bin/redshift-gtk &
