#!/bin/sh
#switch display if external display available
#bash ~/bin/autorandr -c #assuming autorandr works
sh ~/.screenlayout/standard.sh #hardcoded rules
sleep 1 
nitrogen --restore #wallpaper if resolution has changed
#keyboard - language, shortcuts, ctrl instead of caps lock
setxkbmap -model pc105 -layout "us,bg(phonetic)" -option "grp:alt_shift_toggle" 
sleep 1
xmodmap ~/.Xmodmap &
#semafors
(sleep 10s && /usr/bin/sh ~/bin/semafor.sh) &
#var crap
pgrep pidgin &> /dev/null || /usr/bin/pidgin &
pgrep clipit &> /dev/null || /usr/bin/clipit &
pgrep safeeyes &> /dev/null || /usr/bin/safeeyes &
pgrep terminator &> /dev/null || terminator -l work &
#autokey
sleep 60
pgrep autokey-gtk &> /dev/null || /usr/bin/autokey-gtk &
